version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/Vilnius
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - "> 1.3.3, < 1.4"
